#ignore:
#  - "path/to/folder"  # ignore folders and all its contents
#  - "test_*.rb"       # wildcards accepted
#  - "**/*.py"         # glob accepted
#  - "[a-z]+/test_.*"  # regexp accepted

ignore:
  - "demos"
  - "jprotoc/src/main/java/com/salesforce/jprotoc/jdk8/Jdk8Generator.java"
  - "rxgrpc/rxgrpc/src/main/java/com/salesforce/rxgrpc/RxGrpcGenerator.java"

coverage:
  range: 10..80
  round: down
  precision: 2

  status:
    patch: off